/* HIldana. M
 * Hurricane_U2_A5
 * This program informs the user the windspeed of a hurricane(depending 
 * on the category
 * March/23/2018
 */

/**
 *
 * @author Hildana
 */
public class Hurricane_U2_A5 extends javax.swing.JFrame {

    /**
     * Creates new form Hurricane_U2_A5
     */
    public Hurricane_U2_A5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        labelHurricaneCat = new javax.swing.JLabel();
        textHurricaneNum = new javax.swing.JTextField();
        buttonSelect = new javax.swing.JButton();
        labelOutputCat = new javax.swing.JLabel();
        labelWindspeed = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        labelTitle.setText("Hurricane Scale");

        labelHurricaneCat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelHurricaneCat.setText("Enter a hurricane category (1-5):");

        textHurricaneNum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textHurricaneNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textHurricaneNumActionPerformed(evt);
            }
        });

        buttonSelect.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonSelect.setText("Select");
        buttonSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSelectActionPerformed(evt);
            }
        });

        labelOutputCat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        labelWindspeed.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelOutputCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(labelHurricaneCat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(textHurricaneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelTitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(labelWindspeed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(labelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHurricaneCat)
                    .addComponent(textHurricaneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonSelect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelOutputCat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelWindspeed, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textHurricaneNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textHurricaneNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textHurricaneNumActionPerformed

    private void buttonSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSelectActionPerformed
       
       int hurricaneNum; 
       
       //converting string to double and casting it as an integer 
       hurricaneNum = (int) Double.parseDouble (textHurricaneNum.getText());
       
       switch (hurricaneNum)
       {
           case 1: //if it's category 1, display the windspeed
               labelOutputCat.setText("Windspeed for catergory " + hurricaneNum + " are:");
               labelWindspeed.setText("74-95 mph or 64-82 kt or 119-153 km/hr");
               break;
           case 2: //if it's category 2, display the windspeed 
               labelOutputCat.setText("Windspeed for catergory " + hurricaneNum + " are:");
               labelWindspeed.setText("96-110 mph or 83-95 kt or 154-177 km/hr");
               break;
           case 3: //if it's category 3, display the windspeed 
               labelOutputCat.setText("Windspeed for catergory " + hurricaneNum + " are:");
               labelWindspeed.setText("111-130 mph or 96-113 kt or 178-209 km/hr");
               break;
           case 4: //if it's category 4, display the windspeed
               labelOutputCat.setText("Windspeed for catergory " + hurricaneNum + " are:");
               labelWindspeed.setText("131-155 mph or 114-135 kt or 210-249 km/hr"); 
               break;
           case 5: //if it's category 5, display the windspeed 
               labelOutputCat.setText("Windspeed for catergory " + hurricaneNum + " are:");
               labelWindspeed.setText("Greater than 155 mph or 135 kt or 249 km/hr"); 
               break;
           default: //if the category is not 1-5, don't display a windspeed
               labelOutputCat.setText("not 1, 2, 3, 4, 5 "); 
               labelWindspeed.setText(" ");
               break;
       }
     
    }//GEN-LAST:event_buttonSelectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hurricane_U2_A5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hurricane_U2_A5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hurricane_U2_A5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hurricane_U2_A5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hurricane_U2_A5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSelect;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelHurricaneCat;
    private javax.swing.JLabel labelOutputCat;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelWindspeed;
    private javax.swing.JTextField textHurricaneNum;
    // End of variables declaration//GEN-END:variables
}
